apiVersion: v1
kind: Service

metadata:
  name: java-devsecops-service
  namespace: devsecops

spec:
  type: NodePort

  selector:
    app: java-devsecops

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080