name: Java DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  build-and-test:

    name: Build and Test

    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Run tests
        run: mvn clean test

      - name: Build application
        run: mvn package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: java-application
          path: target/java-devsecops-1.0.0.jar


  docker-build:

    name: Docker Build and Security Scan

    runs-on: ubuntu-24.04

    needs: build-and-test

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build JAR
        run: mvn package -DskipTests

      - name: Build Docker image
        run: |
          docker build \
            -t java-devsecops:${{ github.sha }} \
            .

      - name: Show Docker images
        run: docker images

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '0'

      - name: Trivy Docker image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: java-devsecops:${{ github.sha }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '0'